### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by fatoon29** [spyrit/page-builder-bundle#5]
Hello guys, nice project :)
I'd like to know how the routing works withe the created page?
Thanks

**Comment by pyguerder** [comment]
@fatoon29 Hi!
To link to rendered page, you have to implement your own controller action (see `public function show` in the README).
To create links in the created page, you can either use the HTML widget (plain links, nothing special for routing), or create your own widget to store a reference to the page and generate a link at render time.
For example, you can extend the Button widget to store a reference to a page in its configuration. Your widget will be responsible for hydrating that page and pass it to its render template with can then use the id or the slug of the page to generate a route.
Best regards
